version: 0.2

phases:
  install:
    commands:
      - aws --version
      - aws ecr get-login-password --region us-east-1
      - npm install
  build:
    commands:
      - docker build -t 778906112548.dkr.ecr.us-east-1.amazonaws.com/vue-example:latest .
  post_build:
    commands:
      - docker push 778906112548.dkr.ecr.us-east-1.amazonaws.com/vue-example:latest
