version: 0.2

phases:
  install:
    commands:
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 778906112548.dkr.ecr.us-east-1.amazonaws.com
      - npm install
  build:
    commands:
      - docker build -t 778906112548.dkr.ecr.us-east-1.amazonaws.com/test:latest .
  post_build:
    commands:
      - docker push 778906112548.dkr.ecr.us-east-1.amazonaws.com/test:latest
      - printf '[{"name":"hello-vue","imageUri":"%s"}]' 778906112548.dkr.ecr.us-east-1.amazonaws.com/test:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
