version: 0.2

phases:
  install:
    commands:
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 778906112548.dkr.ecr.us-east-1.amazonaws.com
      - npm install
  build:
    commands:
      - docker build -t 778906112548.dkr.ecr.us-east-1.amazonaws.com/hello-vue:latest .
  post_build:
    commands:
      - docker push 778906112548.dkr.ecr.us-east-1.amazonaws.com/hello-vue:latest
      - printf '{"containerDefinitions": [{"essential": true,"image": "%s","name": "web","portMappings": [{"containerPort": 3000,"hostPort": 80}]}],"family": "","volumes": []}' 778906112548.dkr.ecr.us-east-1.amazonaws.com/hello-vue:latest > taskDefinitions.json
artifacts:
    files: taskDefinitions.json
